// Actual product page and host audio; only test response exposes local controller
// references to skip inter-smile waiting / age the inactivity clock. Holds, eyes,
// mouth rendering and native wink timing are NOT accelerated. No production hook.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const BASE=process.env.MIDORI_BASE_URL||'http://127.0.0.1:5178';
const OUT=process.env.MIDORI_TEST_OUTPUT,WAV=process.env.MIDORI_TEST_WAV;
if(!OUT||!WAV)throw Error('Set MIDORI_TEST_OUTPUT and MIDORI_TEST_WAV');fs.mkdirSync(OUT,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--autoplay-policy=no-user-gesture-required']});
const report={checks:[],errors:[],writes:[],holds:[],audio:[],isolation:'Account APIs/SSE blocked. Actual WAV, host analyser, SVG and native controllers. Test-only refs age inactivity / advance inter-smile waiting. Full holds and wink measured in real time.'};
try{const p=await browser.newPage({viewport:{width:1440,height:1000}});p.setDefaultTimeout(25000);p.on('pageerror',e=>report.errors.push(e.message));
await p.route('**/api/**',r=>{if(r.request().method()!=='GET')report.writes.push(r.request().method());return r.abort()});await p.route('**/events*',r=>r.abort());
await p.route('**/__e9-voice.wav',r=>r.fulfill({path:WAV,contentType:'audio/wav'}));
await p.route('**/assets/moon-art/runtime/host.js*',r=>r.fulfill({contentType:'text/javascript',body:'/* Geometry-only night; unrelated WebGL omitted */'}));
await p.route('**/v4-latest-three/sway-expressions.mjs*',async r=>{const res=await r.fetch(),src=await res.text();assert(src.includes('queue.start();'));await r.fulfill({response:res,body:src.replace('sampleSmile:smileSampler(smileData)','random:()=>.99, sampleSmile:smileSampler(smileData)').replace('queue.start();','window.e9Test={queue,get rig(){return rig},expressions,get svg(){return svg},views}; queue.start();')})});
await p.addInitScript(()=>{window.sourceCount=0;const orig=AudioContext.prototype.createMediaElementSource;AudioContext.prototype.createMediaElementSource=function(...a){window.sourceCount++;return orig.apply(this,a)}});
await p.goto(BASE+'/?theme=light');await p.waitForSelector('#gachikoiLayer',{state:'attached'});
const click=id=>p.locator('#'+id).evaluate(e=>e.click());
const ready=()=>p.waitForFunction(()=>document.querySelector('#swayBtn').getAttribute('aria-busy')==='false');
const mode=()=>p.locator('#avatar').getAttribute('data-sway-mode');
async function select(name){for(let i=0;await mode()!==name;i++){assert(i<9,'bounded mode cycle');await click('swayBtn');await ready();}}
const state=name=>p.waitForFunction(name=>document.querySelector('#avatarSwayFrame svg')?.dataset.controllerState===name,name);
await click('freezeBtn');await select('green');await state('idle');await p.mouse.move(1400,20);
const sample=ms=>p.evaluate(async ms=>{const rows=[],start=performance.now();while(performance.now()-start<ms){const s=e9Test.svg;rows.push({at:performance.now(),...s.dataset,weights:[...e9Test.rig.weights],names:e9Test.rig.poseNames,clock:s.getCurrentTime(),audio:document.querySelector('#audio').currentTime});await new Promise(r=>setTimeout(r,20))}return rows},ms);
await p.evaluate(()=>{window.transitions=[];let prev='';window.obs=new MutationObserver(()=>{const s=e9Test.svg,k=[s.dataset.queuePhase,s.dataset.specialIndex,s.dataset.expression].join('/');if(k!==prev){transitions.push({key:k,at:performance.now(),...s.dataset});prev=k}});obs.observe(document.querySelector('#avatarSwayFrame'),{attributes:true,subtree:true,childList:true})});
async function oneSmile(){await state('idle');await p.evaluate(()=>{const q=e9Test.queue;let peak,rest;for(let t=.05;t<100;t+=.05){if(peak===undefined&&q.sampleSmile(t)>.9)peak=t;if(peak!==undefined&&q.sampleSmile(t)===0){rest=t;break}}if(rest===undefined)throw Error('No authored smile');window.smileRest=rest;q.smileElapsed=peak*1000});await p.waitForFunction(()=>e9Test.rig.weights[e9Test.rig.poseNames.indexOf('closedSmile')]>.8);await p.evaluate(()=>e9Test.queue.smileElapsed=smileRest*1000);await p.waitForFunction(()=>e9Test.queue.previousSmile===0);}
for(const [index,special,hold] of [[0,'round',8000],[1,'round',8000],[2,'smile',6000]]){
 for(let i=0;i<3;i++)await oneSmile();await state('wink');await p.waitForTimeout(400);await p.screenshot({path:path.join(OUT,`wink-${index}.png`)});
 await p.waitForFunction(()=>e9Test.svg.dataset.queuePhase==='hold');assert.equal(await p.locator('#avatarSwayFrame svg').getAttribute('data-special'),special);
 const plateau=await sample(150);assert(plateau.every(s=>s.weights[s.names.indexOf(special==='round'?'round':'smileReference')]>.999));
 await p.screenshot({path:path.join(OUT,`${special}-${index}.png`)});await state('idle');
 const duration=await p.evaluate(index=>{const rows=transitions.filter(t=>+t.specialIndex===index);const start=rows.find(t=>t.queuePhase==='hold'),end=rows.find(t=>t.queuePhase==='exit');return{ms:end.at-start.at,start,end}},index);assert(duration.ms>=hold-30&&duration.ms<hold+1000,`${special} full plateau ${duration.ms}`);report.holds.push({special,...duration});
}
report.checks.push('authored completed smiles; slot3 wink before special; native wink and real full 8s/8s/6s plateaus');
const clear=async()=>{await p.evaluate(()=>{const a=document.querySelector('#audio');a.pause();a.removeAttribute('src');a.load()});};
await p.evaluate(()=>e9Test.queue.lastActivity=performance.now()-180001);await state('sleepy');await p.waitForTimeout(600);const sleepy=await sample(500);assert(sleepy.every(s=>s.expression==='sleepy'&&s.sleepy==='true'&&s.mouthPose==='sleepySmall'));await p.screenshot({path:path.join(OUT,'sleepy.png')});
const cycle=await sample(14600);assert(cycle.some(s=>+s.eyeOpenLeft<.01));assert(cycle.some(s=>+s.eyeOpenLeft>.69));assert(cycle.every(s=>s.expression==='sleepy'&&s.sleepyCycleMs==='14400'));report.sleepyCycle={min:Math.min(...cycle.map(s=>+s.eyeOpenLeft)),max:Math.max(...cycle.map(s=>+s.eyeOpenLeft)),samples:cycle.length};report.checks.push('latest-three real 14.4s sleepy cycle reaches full closure and reopens');
await p.evaluate(()=>{const a=document.querySelector('#audio');a.src='/__e9-voice.wav';a.load()});await p.waitForFunction(()=>document.querySelector('#audio').readyState>=3);await click('playBtn');await state('speaking');const voice=await sample(2000);report.audio=voice;assert(voice.some(s=>+s.mouthOpen>.05&&s.audio>0));assert(voice.every(s=>s.expression==='sleepy'&&s.sleepy==='true'&&s.mouthOwner==='speech'));assert(voice.some(s=>s.weights[s.names.indexOf('half')]>0));assert(voice.at(-1).clock>voice[0].clock);await p.screenshot({path:path.join(OUT,'sleepy-speaking.png')});
await click('pauseBtn');await state('sleepy');assert.equal(await p.locator('#avatarSwayFrame svg').getAttribute('data-mouth-pose'),'sleepySmall');await click('pauseBtn');await state('speaking');await clear();await state('sleepy');
await p.mouse.move(1380,35);await state('idle');const wake=await p.evaluate(()=>({...e9Test.svg.dataset}));assert.equal(wake.completedSmiles,'0');assert.equal(wake.specialIndex,'0');assert.equal(wake.expression,'neutral');assert.equal(wake.winkDone,'false');await p.waitForTimeout(500);assert.equal(await p.locator('#avatarSwayFrame svg').getAttribute('data-expression'),'neutral');report.checks.push('aged 180000ms deadline; sleepy exclusive; real voice opens mouth without waking; pause/end restore sleepy; trusted mouse wakes neutral and resets full queue');
await p.evaluate(()=>{const a=document.querySelector('#audio');a.src='/__e9-voice.wav';a.load()});await p.waitForFunction(()=>document.querySelector('#audio').readyState>=3);await click('playBtn');await state('speaking');await click('pauseBtn');await state('held');await click('pauseBtn');await state('speaking');await p.evaluate(()=>document.querySelector('#audio').dispatchEvent(new Event('waiting')));await state('held');await p.waitForTimeout(200);assert.equal(await p.locator('#avatarSwayFrame svg').getAttribute('data-completed-smiles'),'0');await p.evaluate(()=>document.querySelector('#audio').dispatchEvent(new Event('playing')));await state('speaking');await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(150);assert.equal(await p.locator('#avatarSwayFrame svg').getAttribute('data-mouth-open'),'0');await p.emulateMedia({reducedMotion:'no-preference'});await state('speaking');
await p.evaluate(()=>window.oldE9=e9Test);for(const m of ['white','black','swim','classic','lil','off','green']){await click('swayBtn');await ready();assert.equal(await mode(),m)}await state('speaking');assert(await p.evaluate(()=>oldE9.queue.disposed));assert.equal(await p.evaluate(()=>sourceCount),1);await clear();await state('idle');report.checks.push('pause/buffer/resume/reduced; seven-mode audio continuity; old queue disposed; exactly one host MediaElementSource');
await select('off');await p.route('**/v4-latest-three/milky-green-v4-talking.svg',r=>r.abort());await click('swayBtn');await ready();assert.equal(await mode(),'off');await p.unroute('**/v4-latest-three/milky-green-v4-talking.svg');await click('swayBtn');await ready();assert.equal(await mode(),'green');await select('off');let release;const gate=new Promise(r=>release=r);await p.route('**/v4-latest-three/milky-green-v4-talking.svg',async r=>{await gate;await r.continue()});await click('swayBtn');await click('swayBtn');await ready();assert.equal(await mode(),'white');release();await p.waitForTimeout(500);assert.equal(await mode(),'white');await p.unroute('**/v4-latest-three/milky-green-v4-talking.svg');report.checks.push('green failed load/retry and superseded async load retain correct mode');
await select('green');await click('modeToggleBtn');await p.setViewportSize({width:390,height:844});await p.waitForTimeout(600);await p.screenshot({path:path.join(OUT,'night-narrow.png')});const layout=await p.evaluate(()=>{const s=document.querySelector('#avatarSwayFrame svg'),f=s.parentElement.getBoundingClientRect(),d=document.querySelector('#midoriInputDock').getBoundingClientRect();return{f:f.toJSON(),s:s.getBoundingClientRect().toJSON(),d:d.toJSON(),bad:[...s.querySelectorAll('path')].filter(e=>/NaN|Infinity/.test(e.getAttribute('d'))).length,ids:[...document.querySelectorAll('[id]')].map(e=>e.id)}});assert.equal(layout.bad,0);assert.equal(new Set(layout.ids).size,layout.ids.length);assert(Math.abs(layout.f.width-layout.s.width)<.1);assert(layout.d.left>=-1&&layout.d.right<=391);report.checks.push('night/narrow SVG fits host; no NaN or duplicate IDs');
report.transitions=await p.evaluate(()=>transitions);report.sourceCount=await p.evaluate(()=>sourceCount);assert.deepEqual(report.errors,[]);assert.deepEqual(report.writes,[]);report.pass=true;fs.writeFileSync(path.join(OUT,'verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:true,holds:report.holds.map(h=>({special:h.special,ms:h.ms})),sourceCount:report.sourceCount,checks:report.checks}));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
